# Site settings
title: MaxIo's Blog
email: maxio.l.yu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome MaxIo Yu's Blog.
    I will be free!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  MaxIo_Yu
weibo:    ozzie729
github:   maxio-yu
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
